### ISSUE TITLE
`ERR_REQUIRE_ESM` Error in latest version (1.2.2)

### ISSUE THREAD

**Issue by atbe** [qdrant/openapi-typescript-fetch#8]
Hi all,

The version of this package that was released a few hours ago is causing this issue in production. Here's the stacktrace that started getting thrown when our node packages got reinstalled:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /app/ultra-lib/node_modules/json-with-bigint/json-with-bigint.js from /app/ultra-
lib/node_modules/@qdrant/openapi-typescript-fetch/dist/cjs/fetcher.js not supported.
Instead change the require of json-with-bigint.js in /app/ultra-lib/node_modules/@qdrant/openapi-typescript-fetch/dist/cjs/fetche
r.js to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> [as .js] (/app/consumers/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/app/ultra-lib/node_modules/@qdrant/openapi-typescript-fetch/dist/cjs/fetcher.js:5:28)
    at require.extensions.<computed> [as .js] (/app/consumers/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/app/ultra-lib/node_modules/@qdrant/openapi-typescript-fetch/dist/cjs/index.js:4:22)
    at require.extensions.<computed> [as .js] (/app/consumers/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/app/ultra-lib/node_modules/@qdrant/js-client-rest/dist/cjs/api-client.js:4:36)
    at require.extensions.<computed> [as .js] (/app/consumers/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/app/ultra-lib/node_modules/@qdrant/js-client-rest/dist/cjs/qdrant-client.js:5:25)
    at require.extensions.<computed> [as .js] (/app/consumers/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/app/ultra-lib/node_modules/@qdrant/js-client-rest/dist/cjs/index.js:18:26)
    at require.extensions.<computed> [as .js] (/app/consumers/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/app/ultra-lib/src/core/vectors/QdrantVectorStore.ts:5:26)
    at m._compile (/app/consumers/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/app/consumers/node_modules/ts-node/dist/index.js:859:16)
    at Object.<anonymous> (/app/ultra-lib/src/core/vectors/index.ts:4:27)
    at m._compile (/app/consumers/node_modules/ts-node/dist/index.js:857:29)
```

---

I just wanted to let you know, as this package is depended on by https://www.npmjs.com/package/@qdrant/js-client-rest which is [not using a precise version specifier](https://github.com/qdrant/qdrant-js/blob/71791b862f4c43a2606f6fe175507b8d6028ca6e/packages/js-client-rest/package.json#L57).

**Comment by atbe** [comment]
For anyone running into this issue, a quick fix is to pin to the previous version in your `package.json`

```json
  "resolutions": {
    "@qdrant/openapi-typescript-fetch": "1.2.1"
  }
  ```

**Comment by petergoldstein** [comment]
This looks like it's resolved by 1.2.3
